[workspace]
resolver = "1"
members = ["crates/univis_editor"]

[workspace.dependencies]

bevy = { version = "0.17.2", default-features = false, features = [  "bevy_text",
  "bevy_ui",
  "bevy_ui_render",
  "bevy_window",
  "bevy_winit",
  "wayland"
  ]}


